language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.8,<1.9" DB=sqlite
  - DJANGO="Django>=1.9,<1.10" DB=sqlite
  - DJANGO="Django>=1.10,<1.11" DB=sqlite
  - DJANGO="Django>=1.11,<2.0" DB=sqlite
install:
  - export PYTHONPATH=./imagestore/:$PYTHONPATH
  - pip install $DJANGO
  - pip install -r test/testproject/requirements.txt
script:
  - python test/testproject/manage.py test imagestore
